title: Bookmark Collection
description: A collection of interesting bookmarks and articles
baseurl: "/" # 仓库名称作为baseurl
url: "" # 这里会根据GitHub Pages自动设置

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-assets
  - jekyll-paginate

# Exclude from processing
exclude:
  - scripts/
  - requirements.txt
  - CNAME
  - .gitignore
  - Gemfile
  - Gemfile.lock

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

social:
  github: "yiGmMk"

jekyll-archives:
  enabled: [year, month, day, tag]
