name: Bookmark Summary

on:
  push:
    branches:
      - main
    paths:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: mygroup
  cancel-in-progress: false

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bookmark
        uses: actions/checkout@v2
        with:
          path: bookmark

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bookmark/requirements.txt

      - name: Process changes
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}
          OPENAI_API_ENDPOINT: ${{ secrets.OPENAI_API_ENDPOINT }}
        run: |
          ls -al
          ls -al bookmark
          python bookmark/scripts/process_changes.py

      - name: Commit changes to bookmark-summary
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add new summaries" || echo "No changes to commit"
          git push
