name: Website Task

on:
  push:
    branches:
      - main
    paths:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: groupWebsite
  cancel-in-progress: false

permissions:
  contents: write # 允许写入内容（包括标签和发布）

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bookmark
        uses: actions/checkout@v2
        with:
          path: bookmark
      - name: Checkout blog
        uses: actions/checkout@v2
        with:
          path: blog

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bookmark/requirements.txt

      - name: Process changes
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}
          OPENAI_API_ENDPOINT: ${{ secrets.OPENAI_API_ENDPOINT }}
        run: |
          ls -al
          ls -al bookmark
          python bookmark/scripts/translate.py

      # 创建pr
      - name: Commit changes to bookmark
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 提交翻译到仓库
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: master
          delete-branch: false
          title: "提交翻译到仓库"
          body: |
            新增翻译内容
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: yiGmMk
          reviewers: yiGmMk
          team-reviewers: |
            yiGmMk
          milestone: 1
          draft: false
